openapi: 3.0.0
info:
  title: Easybeam Backend API
  version: 1.0.0
  description: OpenAPI specification for Easybeam Backend.

paths:
  /team/{id}/secrets:
    post:
      summary: Add secrets for a team
      operationId: addSecrets
      tags:
        - Team
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Team ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddSecretRequest'
      responses:
        '201':
          description: Secrets added successfully
          content:
            text/plain:
              schema:
                type: string

    delete:
      summary: Delete a specific secret configuration for a team
      operationId: deleteSecrets
      tags:
        - Team
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Team ID
        - in: path
          name: configId
          required: true
          schema:
            type: string
          description: Config ID of the secret to delete
      responses:
        '204':
          description: Secret configuration deleted successfully

  /team/{id}/token:
    post:
      summary: Generate a JWT token for a team
      operationId: generateToken
      tags:
        - Team
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Team ID
      responses:
        '201':
          description: JWT token generated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddTokenResponse'

    delete:
      summary: Remove a JWT token for a team
      operationId: removeToken
      tags:
        - Team
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Team ID
        - in: path
          name: tokenId
          required: true
          schema:
            type: string
          description: Token ID to remove
      responses:
        '204':
          description: JWT token removed successfully

components:
  schemas:
    AddSecretRequest:
      type: object
      properties:
        configId:
          type: string
        secrets:
          type: object
          additionalProperties:
            type: string
    AddTokenResponse:
      type: object
      properties:
        jwtToken:
          type: string
