steps:
  # Step 1: Set the correct permissions for the Gradle Wrapper
  - name: 'busybox'
    args: ['chmod', '+x', 'gradlew']

  - name: 'gcr.io/cloud-builders/gradle'
    entrypoint: './gradlew'  # Use Gradle Wrapper
    args: ['build']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ktor-app:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ktor-app:latest']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'ktor-service', '--image', 'gcr.io/$PROJECT_ID/ktor-app:latest', '--region', 'us-central1', '--platform', 'managed']

images:
  - 'gcr.io/$PROJECT_ID/ktor-app:latest'