steps:
  # Step 1: Build the Ktor application using Gradle
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['build']
    env: ['GRADLE_USER_HOME=/workspace/.gradle']

  # Step 2: Build the Docker container for the Ktor app
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ktor-app:latest', '.']

  # Step 3: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ktor-app:latest']

  # Step 4: Deploy to Google Cloud Run (optional, if you use Cloud Run)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'ktor-service', '--image', 'gcr.io/$PROJECT_ID/ktor-app:latest', '--region', 'us-central1', '--platform', 'managed']

images:
  - 'gcr.io/$PROJECT_ID/ktor-app:latest'