###
GET http://127.0.0.1:8080/api/team/VMe0VFHjyd8k0HJTFp46
Accept: application/json

###
GET https://pollywog-mpkvqutwqq-uc.a.run.app/api/team/VMe0VFHjyd8k0HJTFp46
Accept: application/json

###
GET http://127.0.0.1:8080/api/prompt/abc
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJodHRwOi8vMC4wLjAuMDo4MDgwL2hlbGxvIiwiaXNzIjoiaHR0cDovLzAuMC4wLjA6ODA4MC8iLCJ1c2VySWQiOiJLVjFOQzNnSThRYXJGOThYMlZEOVZoY2FMZlIyIiwidGVhbUlkIjoicU1lU1ppZnRlU1VVQVhsT25BT1MiLCJ0b2tlbklkIjoiNzQyZGY4ZjMtY2Y5Mi00NzI5LTkyZjktMTQ5MDAyZGFlYzAxIiwiaXNzdWVkQXQiOiJUdWUgQXVnIDI5IDE1OjA0OjI2IENFU1QgMjAyMyJ9.spJJs9U398VfypQOxOH0RReZbhXtbFexoSjTqdX7Hlk

{
  "parameters": {
    "journal": 1.1
  }
}